image: docker:latest
services:
- docker:dind

stages:
- build-lost-base
- build-lost
- test-lost
- release-lost

variables:
  # backend stuff
  LOST_BASE_IMAGE: gitlab.l3portal.de:5555/l3p-cv/lost/base/lost-base:0.1
  LOST_TEST_IMAGE: gitlab.l3portal.de:5555/l3p-cv/lost/test/lost:$CI_PIPELINE_ID
  LOST_RELEASE_IMAGE: gitlab.l3portal.de:5555/l3p-cv/lost/release/lost:$CI_COMMIT_TAG
  
before_script:
  - apk add --update nodejs=8.11.4-r0 npm
  - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN gitlab.l3portal.de:5555

build-lost-base:
  stage: build-lost-base
  script:
    - docker build -t $LOST_BASE_IMAGE -f docker/lost-base/Dockerfile .
    - docker push $LOST_BASE_IMAGE
  only: 
    variables:
      - $CI_COMMIT_MESSAGE =~ /lost-base/
  
build-lost:
  stage: build-lost
  script:
    - docker build --build-arg base_image=$LOST_BASE_IMAGE --pull -t $LOST_TEST_IMAGE -f docker/lost/Dockerfile .
    - npm install --prefix /code/frontend/lost -d 
    - npm run build --prefix /code/frontend/lost -d 
    - docker push $LOST_TEST_IMAGE
  except: 
    variables:
      - $CI_COMMIT_MESSAGE =~ /lost-base/

test-lost:
  stage: test-lost
  script:
    - echo "LOST TEST WILL BE HERE IN FUTURE :)"
  except: 
    variables:
      - $CI_COMMIT_MESSAGE =~ /lost-base/


release-lost:
  stage: release-lost
  script:
    - docker pull $LOST_TEST_IMAGE
    - docker tag $LOST_TEST_IMAGE $LOST_RELEASE_IMAGE
    - docker push $LOST_RELEASE_IMAGE
  only:
    - tags
  except: 
    variables:
      - $CI_COMMIT_MESSAGE =~ /lost-base/

