image: docker:latest
services:
- docker:dind

stages:
- build-lost
- test-lost
- release-lost

variables:
  # backend stuff
  LOST_TEST_IMAGE: gitlab.l3portal.de:5555/l3p-cv/lost/test/lost:$CI_PIPELINE_ID
  LOST_RELEASE_IMAGE: gitlab.l3portal.de:5555/l3p-cv/lost/release/lost:$CI_COMMIT_TAG
  
before_script:
  - apk add --update nodejs=8.11.4-r0 npm
  - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN gitlab.l3portal.de:5555

build-lost:
  stage: build-lost
  script:
    - npm run build --prefix frontend/lost -d 
    - docker build --pull -t $LOST_TEST_IMAGE -f docker/lost/Dockerfile .
    - docker push $LOST_TEST_IMAGE

test-lost:
  stage: test-lost
  script:
    - echo "LOST TEST WILL BE HERE IN FUTURE :)"


release-lost:
  stage: release-lost
  script:
    - docker pull $LOST_TEST_IMAGE
    - docker tag $LOST_TEST_IMAGE $LOST_RELEASE_IMAGE
    - docker push $LOST_RELEASE_IMAGE
  only:
    - tags

