image: docker:latest
services:
- docker:dind

stages:
- build-lost-base
- build-lost
- test-lost
- release-lost

variables:
  CI_REGISTRY_BASE_IMAGE: $CI_REGISTRY_BASE_IMAGE:0.1
  CI_REGISTRY_TEST_IMAGE: : $CI_REGISTRY_TEST_IMAGE:$CI_COMMIT_REF_SLUG
  CI_REGISTRY_IMAGE: $CI_REGISTRY_IMAGE:$CI_COMMIT_TAG
  LOST_VERSION: $CI_COMMIT_REF_SLUG

  
before_script:
  - apk add --update nodejs=8.14.0-r0 npm
  - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY

build-lost-base:
  stage: build-lost-base
  script:
    - docker build -t $CI_REGISTRY_BASE_IMAGE -f docker/lost-base/Dockerfile .
    - docker push $CI_REGISTRY_BASE_IMAGE
  only: 
    variables:
      - $CI_COMMIT_MESSAGE =~ /lost-base/
build-lost:
  stage: build-lost
  script:
    - npm install --prefix frontend/lost/src/tools/sia -d 
    - npm install --prefix frontend/lost/src/tools/pipeline -d
    - npm install --prefix frontend/lost -d 
    - CI=false npm run build --prefix frontend/lost -d 
    - rm -rf frontend/lost/node_modules
    - rm -rf frontend/lost/src/tools/sia/node_modules
    - rm -rf frontend/lost/src/tools/pipeline/node_modules
    - docker build --build-arg base_image=$CI_REGISTRY_BASE_IMAGE --pull -t $CI_REGISTRY_TEST_IMAGE -f docker/lost/Dockerfile .
    - docker push $CI_REGISTRY_TEST_IMAGE
  except: 
    variables:
      - $CI_COMMIT_MESSAGE =~ /lost-base/

test-lost:
  stage: test-lost
  before_script: 
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN gitlab.l3portal.de:5555
    - apk add --no-cache py-pip
    - pip install docker-compose
  script:
    - cd docker/compose && docker-compose run -e LOST_VERSION=$LOST_VERSION lost bash /pytest.sh
  except: 
    variables:
      - $CI_COMMIT_MESSAGE =~ /lost-base/


release-lost:
  stage: release-lost
  script:
    - docker pull $CI_REGISTRY_TEST_IMAGE
    - docker tag $CI_REGISTRY_TEST_IMAGE $CI_REGISTRY_IMAGE
    - docker push $CI_REGISTRY_IMAGE
  only:
    - tags
  except: 
    variables:
      - $CI_COMMIT_MESSAGE =~ /lost-base/

